// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import "server-only"

export const ExamplesIndex: Record<string, Record<string, any>> = {
  radix: {
    "status-notify-demo": {
      name: "status-notify-demo",
      filePath: "examples/radix/status-notify-demo.tsx",
    },
  },
}
