// @ts-nocheck
// This file is autogenerated by scripts/build-registry.mts
// Do not edit this file directly.
import "server-only"

import * as React from "react"

export const Components: Record<string, any> = {
  "status-notify-demo": React.lazy(async () => {
    const mod = await import("@/examples/radix/status-notify-demo")
    const exportName =
      Object.keys(mod).find(
        (key) => typeof mod[key] === "function" || typeof mod[key] === "object"
      ) || "status-notify-demo"
    return { default: mod.default || mod[exportName] }
  }),
}
